/**
 * Auth.js v5 catch-all route — handles GET + POST for /api/auth/* endpoints
 * (csrf, callback, session, signin, signout, etc.). The handlers are
 * generated by NextAuth() in lib/auth.ts.
 */

import { handlers } from "@/lib/auth";

export const { GET, POST } = handlers;
