/**
 * sec-012 — `savePushSubscriptionAction` trusted a client-supplied endpoint.
 *
 * WHAT IT WAS. The action upserted on `PushSubscription.endpoint`, which is
 * globally unique and carries no `companyId`, and the conflict branch was
 *
 *     update: { userId: session.user.id, p256dh: keys.p256dh, auth: keys.auth }
 *
 * so whoever posted the string became the owner of that row. Any authenticated
 * user of any workspace who learned another person's endpoint URL could repoint
 * it at themselves: the victim's device silently stops receiving push for
 * mentions, DMs and task assignments with nothing in the UI to explain it, and
 * the attacker's own pushes are dispatched to the victim's hardware. A
 * cross-tenant write keyed on an unverified client-supplied id.
 *
 * WHAT THE REASSIGNMENT WAS FOR, and why it is not simply deleted. The comment
 * justified it with a device changing hands — A logs out of a shared browser, B
 * logs in and enables push. That browser's service-worker subscription outlives
 * the logout, so `pushManager.subscribe()` hands B *A's* endpoint back, and a
 * flat refusal would leave B unable to ever enable push on that machine, with no
 * way out from the UI.
 *
 * THE DISTINCTION THE FIX DRAWS. B in that story holds the subscription itself,
 * so B posts the stored `p256dh` + `auth` verbatim — those keys are generated by
 * the browser and never leave it. An attacker holding only the URL posts their
 * OWN keys, because their browser gave them a different subscription. So the
 * takeover is granted on proof of the device (keys equal), never on the string
 * alone. A re-subscribed browser produces a brand-new endpoint, so the ordinary
 * handoff goes through `create` and never reaches this branch at all.
 *
 * The write gate is part of the same finding: without it the action is an
 * unmetered probe (and an unbounded row-creation path) for an authenticated
 * attacker.
 */

import { beforeEach, describe, expect, it, vi } from "vitest";

const H = vi.hoisted(() => {
  const calls: Array<{ path: string; args: Record<string, unknown> }> = [];
  const results = new Map<string, unknown>();
  const consumed: Array<{ bucket: string; key: string }> = [];
  const gate = { allowed: true as boolean, error: undefined as string | undefined };

  const OPS = [
    "findUnique",
    "findFirst",
    "findMany",
    "count",
    "create",
    "update",
    "updateMany",
    "upsert",
    "delete",
    "deleteMany",
  ];

  type Op = (args?: Record<string, unknown>) => Promise<unknown>;
  const delegate: Record<string, Op> = {};
  for (const op of OPS) {
    const path = `pushSubscription.${op}`;
    delegate[op] = async (args?: Record<string, unknown>) => {
      calls.push({ path, args: args ?? {} });
      const canned = results.get(path);
      return typeof canned === "function"
        ? (canned as (a: Record<string, unknown>) => unknown)(args ?? {})
        : canned;
    };
  }

  return {
    db: { pushSubscription: delegate },
    calls,
    results,
    consumed,
    gate,
    session: { value: null as unknown },
  };
});

vi.mock("@/lib/db", () => ({ db: H.db }));
vi.mock("@/lib/auth", () => ({ auth: async () => H.session.value }));
vi.mock("@/lib/sentry-server", () => ({ captureServerError: vi.fn() }));
vi.mock("next/headers", () => ({
  headers: async () => ({ get: (name: string) => (name === "user-agent" ? "UA/1.0" : null) }),
}));
// A recorder, not the real token bucket: the property under test is "this
// action participates in the write policy", not the number in lib/rate-limit.ts.
vi.mock("@/lib/rate-limit", () => ({
  limiters: {
    write: {
      consume: (key: string) => {
        H.consumed.push({ bucket: "write", key });
        return { allowed: H.gate.allowed, error: H.gate.error };
      },
    },
  },
}));

import { savePushSubscriptionAction } from "@/lib/actions/push";

const ENDPOINT = "https://fcm.googleapis.com/fcm/send/cDhIa9xZ8kE:APA91bF-victim-device-token";
const VICTIM = { id: "u-victim", p256dh: "victim-p256dh", auth: "victim-auth" };
const ATTACKER = "u-attacker";

function signedIn(id: string, companyId = "c-attacker") {
  H.session.value = { user: { id, companyId, role: "member" } };
}

const WRITE_OPS = ["create", "update", "updateMany", "upsert", "delete", "deleteMany"];

/** Every userId this call would write onto a PushSubscription row. */
function writtenUserIds(): string[] {
  const out: string[] = [];
  for (const c of H.calls) {
    const [, op] = c.path.split(".");
    if (!WRITE_OPS.includes(op ?? "")) continue;
    for (const key of ["data", "create", "update"]) {
      const payload = c.args[key] as Record<string, unknown> | undefined;
      if (payload && typeof payload.userId === "string") out.push(payload.userId);
    }
  }
  return out;
}

function rowWrites(): number {
  return H.calls.filter((c) => WRITE_OPS.includes(c.path.split(".")[1] ?? "")).length;
}

/** The victim's row, as the DB would hand it back for any `select`. */
function victimRowExists() {
  H.results.set("pushSubscription.findUnique", () => ({
    id: "ps-1",
    userId: VICTIM.id,
    endpoint: ENDPOINT,
    p256dh: VICTIM.p256dh,
    auth: VICTIM.auth,
    userAgent: "Victim-UA/1.0",
  }));
  H.results.set("pushSubscription.findFirst", () => ({
    id: "ps-1",
    userId: VICTIM.id,
    endpoint: ENDPOINT,
    p256dh: VICTIM.p256dh,
    auth: VICTIM.auth,
  }));
}

beforeEach(() => {
  H.calls.length = 0;
  H.consumed.length = 0;
  H.results.clear();
  H.gate.allowed = true;
  H.gate.error = undefined;
  signedIn(ATTACKER);
});

describe("sec-012 — an endpoint someone else owns cannot be claimed with the string alone", () => {
  it("does not reassign a foreign subscription to the caller", async () => {
    victimRowExists();

    const res = await savePushSubscriptionAction({
      endpoint: ENDPOINT,
      keys: { p256dh: "attacker-p256dh", auth: "attacker-auth" },
    });

    expect(
      writtenUserIds(),
      "the row belongs to a user in another workspace; posting its URL must not move it"
    ).not.toContain(ATTACKER);
    expect(res.success, "the claim is refused, not quietly honoured").toBe(false);
  });

  it("leaves the victim's keys intact, so their device keeps decrypting its push", async () => {
    victimRowExists();

    await savePushSubscriptionAction({
      endpoint: ENDPOINT,
      keys: { p256dh: "attacker-p256dh", auth: "attacker-auth" },
    });

    const wrote = H.calls
      .filter((c) => WRITE_OPS.includes(c.path.split(".")[1] ?? ""))
      .flatMap((c) => ["data", "create", "update"].map((k) => c.args[k]))
      .filter((p): p is Record<string, unknown> => !!p);
    for (const payload of wrote) {
      expect(payload.p256dh, "overwriting the keys breaks the victim's device").not.toBe(
        "attacker-p256dh"
      );
    }
  });

  it("still takes the row over for a browser that proves it holds the subscription", async () => {
    // The documented change-of-hands case: same device, so the keys the client
    // posts are byte-identical to the stored ones.
    victimRowExists();

    const res = await savePushSubscriptionAction({
      endpoint: ENDPOINT,
      keys: { p256dh: VICTIM.p256dh, auth: VICTIM.auth },
    });

    expect(res.success).toBe(true);
    expect(writtenUserIds()).toContain(ATTACKER);
  });

  it("still refreshes the caller's own subscription", async () => {
    signedIn(VICTIM.id, "c-victim");
    victimRowExists();

    const res = await savePushSubscriptionAction({
      endpoint: ENDPOINT,
      keys: { p256dh: "rotated-p256dh", auth: "rotated-auth" },
    });

    expect(res.success).toBe(true);
    expect(writtenUserIds()).toContain(VICTIM.id);
  });

  it("still stores a subscription nobody owns yet", async () => {
    H.results.set("pushSubscription.findUnique", () => null);
    H.results.set("pushSubscription.findFirst", () => null);

    const res = await savePushSubscriptionAction({
      endpoint: "https://fcm.googleapis.com/fcm/send/fresh-device-token",
      keys: { p256dh: "fresh-p256dh", auth: "fresh-auth" },
    });

    expect(res.success).toBe(true);
    expect(writtenUserIds()).toEqual([ATTACKER]);
  });

  it("spends the write budget, so the endpoint space cannot be probed for free", async () => {
    H.results.set("pushSubscription.findUnique", () => null);

    await savePushSubscriptionAction({
      endpoint: ENDPOINT,
      keys: { p256dh: "p", auth: "a" },
    });

    expect(H.consumed).toEqual([{ bucket: "write", key: ATTACKER }]);
  });

  it("writes nothing when the write budget is spent", async () => {
    H.gate.allowed = false;
    H.gate.error = "Too many requests";
    H.results.set("pushSubscription.findUnique", () => null);

    const res = await savePushSubscriptionAction({
      endpoint: ENDPOINT,
      keys: { p256dh: "p", auth: "a" },
    });

    expect(res.success).toBe(false);
    expect(rowWrites()).toBe(0);
  });
});
