import { v4 as uuid } from "uuid";
import type { User, Company, Transaction, Task, Activity, Notification } from "./types";
import { EXPENSE_CATEGORIES, INVESTMENT_CATEGORIES } from "./types";

export function seedData() {
  const companyId = uuid();
  const saqibId = uuid();
  const aliId = uuid();
  const ahmedId = uuid();
  const fatimaId = uuid();
  const sarahId = uuid();

  const company: Company = {
    id: companyId,
    name: "Nimbus Labs",
    industry: "SaaS / B2B Software",
    currency: "PKR",
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: saqibId,
  };

  const users: User[] = [
    {
      id: saqibId,
      name: "Saqib Nawaz",
      email: "demo@founderflow.app",
      password: "demo123",
      role: "admin",
      companyId,
      createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: aliId,
      name: "Ali Raza",
      email: "ali@nimbus.app",
      password: "demo123",
      role: "cofounder",
      companyId,
      createdAt: new Date(Date.now() - 85 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: ahmedId,
      name: "Ahmed Khan",
      email: "ahmed@nimbus.app",
      password: "demo123",
      role: "cofounder",
      companyId,
      createdAt: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: fatimaId,
      name: "Fatima Sheikh",
      email: "fatima@nimbus.app",
      password: "demo123",
      role: "member",
      companyId,
      createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: sarahId,
      name: "Sarah Malik",
      email: "sarah@nimbus.app",
      password: "demo123",
      role: "member",
      companyId,
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ];

  const daysAgo = (n: number) => new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();

  const investments: Transaction[] = [
    {
      id: uuid(),
      companyId,
      type: "investment",
      amount: 500000,
      category: "Seed Capital",
      description: "Initial seed funding from founder",
      date: daysAgo(88),
      addedBy: saqibId,
      addedByName: "Saqib Nawaz",
      createdAt: daysAgo(88),
    },
    {
      id: uuid(),
      companyId,
      type: "investment",
      amount: 350000,
      category: "Personal Investment",
      description: "Co-founder contribution",
      date: daysAgo(85),
      addedBy: aliId,
      addedByName: "Ali Raza",
      createdAt: daysAgo(85),
    },
    {
      id: uuid(),
      companyId,
      type: "investment",
      amount: 300000,
      category: "Personal Investment",
      description: "Co-founder contribution",
      date: daysAgo(80),
      addedBy: ahmedId,
      addedByName: "Ahmed Khan",
      createdAt: daysAgo(80),
    },
    {
      id: uuid(),
      companyId,
      type: "investment",
      amount: 200000,
      category: "Revenue Reinvestment",
      description: "Q1 revenue reinvested into product",
      date: daysAgo(45),
      addedBy: saqibId,
      addedByName: "Saqib Nawaz",
      createdAt: daysAgo(45),
    },
    {
      id: uuid(),
      companyId,
      type: "investment",
      amount: 150000,
      category: "External Investor",
      description: "Angel investor contribution",
      date: daysAgo(20),
      addedBy: saqibId,
      addedByName: "Saqib Nawaz",
      createdAt: daysAgo(20),
    },
  ];

  const expenses: Transaction[] = [
    {
      id: uuid(),
      companyId,
      type: "expense",
      amount: 75000,
      category: "Office Rent",
      description: "Monthly co-working space",
      date: daysAgo(85),
      addedBy: saqibId,
      addedByName: "Saqib Nawaz",
      createdAt: daysAgo(85),
    },
    {
      id: uuid(),
      companyId,
      type: "expense",
      amount: 120000,
      category: "Equipment",
      description: "MacBooks for development team",
      date: daysAgo(82),
      addedBy: aliId,
      addedByName: "Ali Raza",
      createdAt: daysAgo(82),
    },
    {
      id: uuid(),
      companyId,
      type: "expense",
      amount: 25000,
      category: "Software",
      description: "Annual SaaS subscriptions",
      date: daysAgo(78),
      addedBy: ahmedId,
      addedByName: "Ahmed Khan",
      createdAt: daysAgo(78),
    },
    {
      id: uuid(),
      companyId,
      type: "expense",
      amount: 75000,
      category: "Office Rent",
      description: "Monthly co-working space",
      date: daysAgo(55),
      addedBy: saqibId,
      addedByName: "Saqib Nawaz",
      createdAt: daysAgo(55),
    },
    {
      id: uuid(),
      companyId,
      type: "expense",
      amount: 45000,
      category: "Marketing",
      description: "Google Ads campaign",
      date: daysAgo(50),
      addedBy: aliId,
      addedByName: "Ali Raza",
      createdAt: daysAgo(50),
    },
    {
      id: uuid(),
      companyId,
      type: "expense",
      amount: 180000,
      category: "Salaries",
      description: "Team salaries for May",
      date: daysAgo(40),
      addedBy: saqibId,
      addedByName: "Saqib Nawaz",
      createdAt: daysAgo(40),
    },
    {
      id: uuid(),
      companyId,
      type: "expense",
      amount: 30000,
      category: "Travel",
      description: "Client meetings in Karachi",
      date: daysAgo(35),
      addedBy: ahmedId,
      addedByName: "Ahmed Khan",
      createdAt: daysAgo(35),
    },
    {
      id: uuid(),
      companyId,
      type: "expense",
      amount: 15000,
      category: "Food & Beverages",
      description: "Team lunch and snacks",
      date: daysAgo(28),
      addedBy: fatimaId,
      addedByName: "Fatima Sheikh",
      createdAt: daysAgo(28),
    },
    {
      id: uuid(),
      companyId,
      type: "expense",
      amount: 75000,
      category: "Office Rent",
      description: "Monthly co-working space",
      date: daysAgo(25),
      addedBy: saqibId,
      addedByName: "Saqib Nawaz",
      createdAt: daysAgo(25),
    },
    {
      id: uuid(),
      companyId,
      type: "expense",
      amount: 60000,
      category: "Marketing",
      description: "Social media campaign Q2",
      date: daysAgo(18),
      addedBy: aliId,
      addedByName: "Ali Raza",
      createdAt: daysAgo(18),
    },
    {
      id: uuid(),
      companyId,
      type: "expense",
      amount: 22000,
      category: "Legal & Accounting",
      description: "Quarterly accounting fees",
      date: daysAgo(12),
      addedBy: saqibId,
      addedByName: "Saqib Nawaz",
      createdAt: daysAgo(12),
    },
    {
      id: uuid(),
      companyId,
      type: "expense",
      amount: 185000,
      category: "Salaries",
      description: "Team salaries for June",
      date: daysAgo(8),
      addedBy: saqibId,
      addedByName: "Saqib Nawaz",
      createdAt: daysAgo(8),
    },
    {
      id: uuid(),
      companyId,
      type: "expense",
      amount: 8500,
      category: "Utilities",
      description: "Internet and electricity",
      date: daysAgo(5),
      addedBy: fatimaId,
      addedByName: "Fatima Sheikh",
      createdAt: daysAgo(5),
    },
    {
      id: uuid(),
      companyId,
      type: "expense",
      amount: 18000,
      category: "Software",
      description: "Design tools and analytics",
      date: daysAgo(3),
      addedBy: sarahId,
      addedByName: "Sarah Malik",
      createdAt: daysAgo(3),
    },
  ];

  const transactions = [...investments, ...expenses];

  // Single demo project so every seeded task satisfies the Task.projectId
  // contract. This is the localStorage seed used by the legacy demo mode —
  // it doesn't touch the real DB, so the projectId only needs to be a
  // stable non-empty string.
  const defaultProjectId = uuid();

  const tasks: Task[] = [
    {
      id: uuid(),
      companyId,
      projectId: defaultProjectId,
      title: "Finalize Q3 product roadmap",
      description: "Review feature requests and prioritize for next quarter",
      status: "in_progress",
      priority: "high",
      assignedTo: aliId,
      assignedToName: "Ali Raza",
      assignedBy: saqibId,
      assignedByName: "Saqib Nawaz",
      deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: daysAgo(5),
    },
    {
      id: uuid(),
      companyId,
      projectId: defaultProjectId,
      title: "Design new landing page",
      description: "Create high-converting hero section with new branding",
      status: "in_progress",
      priority: "high",
      assignedTo: sarahId,
      assignedToName: "Sarah Malik",
      assignedBy: aliId,
      assignedByName: "Ali Raza",
      deadline: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: daysAgo(3),
    },
    {
      id: uuid(),
      companyId,
      projectId: defaultProjectId,
      title: "Customer interviews — top 10 users",
      description: "Schedule and conduct discovery interviews",
      status: "pending",
      priority: "medium",
      assignedTo: ahmedId,
      assignedToName: "Ahmed Khan",
      assignedBy: saqibId,
      assignedByName: "Saqib Nawaz",
      deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: daysAgo(2),
    },
    {
      id: uuid(),
      companyId,
      projectId: defaultProjectId,
      title: "Prepare investor pitch deck v2",
      description: "Update financials and traction metrics for Series A",
      status: "pending",
      priority: "urgent",
      assignedTo: saqibId,
      assignedToName: "Saqib Nawaz",
      assignedBy: saqibId,
      assignedByName: "Saqib Nawaz",
      deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: daysAgo(1),
    },
    {
      id: uuid(),
      companyId,
      projectId: defaultProjectId,
      title: "Hire backend engineer",
      description: "Source candidates and conduct first round interviews",
      status: "pending",
      priority: "medium",
      assignedTo: fatimaId,
      assignedToName: "Fatima Sheikh",
      assignedBy: ahmedId,
      assignedByName: "Ahmed Khan",
      deadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: daysAgo(6),
    },
    {
      id: uuid(),
      companyId,
      projectId: defaultProjectId,
      title: "Setup CI/CD pipeline",
      description: "Migrate from manual deploys to GitHub Actions",
      status: "completed",
      priority: "high",
      assignedTo: ahmedId,
      assignedToName: "Ahmed Khan",
      assignedBy: saqibId,
      assignedByName: "Saqib Nawaz",
      deadline: daysAgo(2),
      createdAt: daysAgo(15),
      completedAt: daysAgo(2),
    },
    {
      id: uuid(),
      companyId,
      projectId: defaultProjectId,
      title: "Launch beta with 20 customers",
      description: "Coordinate beta launch and gather initial feedback",
      status: "completed",
      priority: "urgent",
      assignedTo: aliId,
      assignedToName: "Ali Raza",
      assignedBy: saqibId,
      assignedByName: "Saqib Nawaz",
      deadline: daysAgo(20),
      createdAt: daysAgo(40),
      completedAt: daysAgo(18),
    },
    {
      id: uuid(),
      companyId,
      projectId: defaultProjectId,
      title: "Setup analytics dashboard",
      description: "Integrate Mixpanel and create internal metrics dashboard",
      status: "completed",
      priority: "low",
      assignedTo: sarahId,
      assignedToName: "Sarah Malik",
      assignedBy: ahmedId,
      assignedByName: "Ahmed Khan",
      deadline: daysAgo(10),
      createdAt: daysAgo(25),
      completedAt: daysAgo(11),
    },
  ];

  const activities: Activity[] = [
    {
      id: uuid(),
      companyId,
      type: "company_created",
      message: 'Saqib Nawaz created the company "Nimbus Labs"',
      userId: saqibId,
      userName: "Saqib Nawaz",
      createdAt: daysAgo(90),
    },
    {
      id: uuid(),
      companyId,
      type: "user_joined",
      message: "Ali Raza joined as Co-Founder",
      userId: aliId,
      userName: "Ali Raza",
      createdAt: daysAgo(85),
    },
    {
      id: uuid(),
      companyId,
      type: "investment_added",
      message: "Saqib Nawaz added investment of 500,000 PKR",
      userId: saqibId,
      userName: "Saqib Nawaz",
      createdAt: daysAgo(88),
    },
    {
      id: uuid(),
      companyId,
      type: "user_joined",
      message: "Ahmed Khan joined as Co-Founder",
      userId: ahmedId,
      userName: "Ahmed Khan",
      createdAt: daysAgo(80),
    },
    {
      id: uuid(),
      companyId,
      type: "task_completed",
      message: 'Ahmed Khan completed "Setup CI/CD pipeline"',
      userId: ahmedId,
      userName: "Ahmed Khan",
      createdAt: daysAgo(2),
    },
    {
      id: uuid(),
      companyId,
      type: "expense_added",
      message: "Saqib Nawaz added expense of 185,000 PKR for Salaries",
      userId: saqibId,
      userName: "Saqib Nawaz",
      createdAt: daysAgo(8),
    },
    {
      id: uuid(),
      companyId,
      type: "task_assigned",
      message: 'Saqib Nawaz assigned "Finalize Q3 product roadmap" to Ali Raza',
      userId: saqibId,
      userName: "Saqib Nawaz",
      createdAt: daysAgo(5),
    },
    {
      id: uuid(),
      companyId,
      type: "expense_added",
      message: "Sarah Malik added expense of 18,000 PKR for Software",
      userId: sarahId,
      userName: "Sarah Malik",
      createdAt: daysAgo(3),
    },
    {
      id: uuid(),
      companyId,
      type: "investment_added",
      message: "Saqib Nawaz added investment of 150,000 PKR",
      userId: saqibId,
      userName: "Saqib Nawaz",
      createdAt: daysAgo(20),
    },
    {
      id: uuid(),
      companyId,
      type: "task_assigned",
      message: 'Ali Raza assigned "Design new landing page" to Sarah Malik',
      userId: aliId,
      userName: "Ali Raza",
      createdAt: daysAgo(3),
    },
  ];

  const notifications: Notification[] = [
    {
      id: uuid(),
      userId: saqibId,
      companyId,
      title: "Task Completed",
      message: 'Ahmed Khan completed "Setup CI/CD pipeline"',
      type: "success",
      read: false,
      link: "/tasks",
      createdAt: daysAgo(2),
    },
    {
      id: uuid(),
      userId: saqibId,
      companyId,
      title: "New Expense",
      message: "Sarah Malik logged 18,000 PKR",
      type: "warning",
      read: false,
      link: "/expenses",
      createdAt: daysAgo(3),
    },
    {
      id: uuid(),
      userId: saqibId,
      companyId,
      title: "New Expense",
      message: "Fatima Sheikh logged 8,500 PKR",
      type: "warning",
      read: true,
      link: "/expenses",
      createdAt: daysAgo(5),
    },
  ];

  return {
    company,
    users,
    companies: [company],
    transactions,
    tasks,
    activities,
    notifications,
  };
}
