"use server";

/**
 * Web Push subscription lifecycle — the browser subscribes/unsubscribes on the
 * client and calls these to persist/remove the subscription server-side.
 * Scoped to the signed-in user; endpoints are unique per device.
 */

import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { limiters } from "@/lib/rate-limit";
import { PushSubscriptionSchema } from "@/lib/schemas/push";
import { captureServerError } from "@/lib/sentry-server";

import type { ActionResult } from "@/lib/actions/types";

export async function savePushSubscriptionAction(input: unknown): Promise<ActionResult> {
  const session = await auth();
  if (!session?.user?.id) return { success: false, error: "Not authenticated" };

  // `endpoint` is a client-supplied id for a globally unique row, so this gate
  // is also what stops the action being used to probe for other people's
  // endpoints, or to insert rows without bound (sec-012).
  const gate = limiters.write.consume(session.user.id);
  if (!gate.allowed) return { success: false, error: gate.error ?? "Too many requests" };

  const parsed = PushSubscriptionSchema.safeParse(input);
  if (!parsed.success) return { success: false, error: "Invalid subscription" };
  const { endpoint, keys } = parsed.data;
  const userId = session.user.id;

  try {
    const ua = (await headers()).get("user-agent")?.slice(0, 300) ?? null;

    // Endpoint is globally unique and the row carries no companyId, so an
    // upsert keyed on it ALONE handed the row to whoever posted the string —
    // a user of any workspace could repoint a stranger's device at themselves
    // and silently kill that person's notifications (sec-012). Read the row
    // first and decide who is allowed to write it.
    const existing = await db.pushSubscription.findUnique({
      where: { endpoint },
      select: { userId: true, p256dh: true, auth: true },
    });

    if (!existing) {
      // create(), not upsert(): if a row for this endpoint lands between the
      // read above and this write, the unique constraint must fail the request
      // rather than overwrite whatever just arrived.
      await db.pushSubscription.create({
        data: { userId, endpoint, p256dh: keys.p256dh, auth: keys.auth, userAgent: ua },
      });
      return { success: true, data: undefined };
    }

    // A device that changed hands — A logs out of a shared browser, B logs in
    // and enables push — still works, and it is the only reason this branch
    // can reassign at all. That browser's service-worker subscription outlives
    // the logout, so B's client posts the STORED keys verbatim: p256dh/auth are
    // generated by the browser and never leave it. Someone who merely knows the
    // URL cannot produce them, because their own browser handed them a
    // different subscription. So the handover is granted on proof of the
    // device, never on the string. (A browser that genuinely re-subscribes gets
    // a NEW endpoint and goes through create() above, so this is only ever the
    // shared-browser case.)
    const sameDevice = existing.p256dh === keys.p256dh && existing.auth === keys.auth;
    if (existing.userId !== userId && !sameDevice) {
      // Deliberately the same message as the catch below, so the REASON for the
      // refusal does not leak: a caller cannot tell "someone else owns this" from
      // "the write failed".
      //
      // IT IS NOT INDISTINGUISHABLE, and an earlier version of this comment claimed
      // it was ("the caller learns nothing about whether that endpoint is
      // registered"). The message is uniform; the OUTCOME is not. An unregistered
      // endpoint takes the create path above and returns success, this one returns
      // failure — so one bit, registered-to-someone-else or not, is still readable
      // off the `success` flag. Closing that would mean returning success for a
      // write that did not happen, which is a worse lie than the bit is worth. What
      // prices it instead is the write limiter at the top of this action: probing
      // costs 60 attempts a minute against endpoints an attacker must already hold.
      return { success: false, error: "Couldn't enable push notifications right now." };
    }

    await db.pushSubscription.update({
      where: { endpoint },
      data: { userId, p256dh: keys.p256dh, auth: keys.auth },
    });
    return { success: true, data: undefined };
  } catch (e) {
    captureServerError(e, { action: "savePushSubscription" });
    return { success: false, error: "Couldn't enable push notifications right now." };
  }
}

export async function deletePushSubscriptionAction(endpoint: string): Promise<ActionResult> {
  const session = await auth();
  if (!session?.user?.id) return { success: false, error: "Not authenticated" };
  try {
    await db.pushSubscription.deleteMany({ where: { endpoint, userId: session.user.id } });
    return { success: true, data: undefined };
  } catch (e) {
    captureServerError(e, { action: "deletePushSubscription" });
    return { success: false, error: "Couldn't disable push notifications right now." };
  }
}
