/**
 * rep-006 — the two download buttons on /reports must describe the SAME ledger.
 *
 * WHAT WENT WRONG. The Transaction History table in the PDF was built with
 * `t.description.length > 30 ? t.description.slice(0, 30) + "…" : t.description`,
 * while the .xlsx generated by the button immediately beside it wrote
 * `t.description` in full. Transaction descriptions validate up to 500 characters
 * (lib/schemas/transaction.ts), so 45 characters is an ordinary length rather
 * than an outlier: "Cloud hosting renewal for the analytics stack" arrived in the
 * investor PDF as "Cloud hosting renewal for the a…", with nothing to say what
 * was cut or that anything had been.
 *
 * It matters more than a cosmetic clip because of WHICH artefact loses the
 * detail. The PDF is the one this product sells as investor-ready
 * (lib/i18n/strings.ts `loginFeature3`), and two files generated by two adjacent
 * buttons that disagree about the same row is precisely the inconsistency an
 * auditor notices. jspdf-autotable wraps cell text by itself, so the truncation
 * was a choice and not a layout necessity.
 *
 * WHY THESE FUNCTIONS EXIST. The row builders used to be inline `.map()` calls
 * inside `exportPDF` and `exportExcel`, which is the same shape money-010 was:
 * the figures were computed twice, so the mislabelled row had to be fixed twice.
 * `pdfTransactionRows` / `excelTransactionRows` are the single definitions both
 * exporters map over, and the parity case below fails if a later edit reopens the
 * gap in either direction.
 *
 * Run as: npx cross-env TZ=America/Bogota vitest run tests/app/reports/reports-export-fidelity.test.ts
 */

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  TXN_DESCRIPTION_COL,
  excelTransactionRows,
  pdfTransactionRows,
} from "@/app/(app)/reports/reports-client";
import type { Transaction } from "@/lib/types";

const money = (amount: number) => `PKR ${amount.toFixed(2)}`;

/** 45 characters — the length the audit's own repro used. */
const LONG = "Cloud hosting renewal for the analytics stack";

function txn(over: Partial<Transaction> = {}): Transaction {
  return {
    id: "t1",
    companyId: "c1",
    type: "expense",
    amount: 1200,
    category: "Infrastructure",
    description: LONG,
    date: "2026-09-12T00:00:00.000Z",
    addedBy: "u1",
    addedByName: "Ayesha",
    createdAt: "2026-09-12T00:00:00.000Z",
    ...over,
  } as Transaction;
}

describe("the fixture is long enough to be cut", () => {
  it("is over the 30-character limit the PDF used to apply", () => {
    // Guard the guard: at 30 characters or fewer every assertion below passes
    // against the unfixed code and the file reads as coverage of nothing.
    expect(LONG.length).toBe(45);
    expect(LONG.length).toBeGreaterThan(30);
  });
});

describe("pdfTransactionRows (rep-006)", () => {
  it("carries the description the user typed, in full", () => {
    const [row] = pdfTransactionRows([txn()], money);
    expect(row[TXN_DESCRIPTION_COL]).toBe(LONG);
  });

  it("does not append an ellipsis to a description that was never cut", () => {
    const [row] = pdfTransactionRows([txn()], money);
    expect(row[TXN_DESCRIPTION_COL]).not.toContain("…");
  });

  it("still renders the other five cells the table needs", () => {
    const [row] = pdfTransactionRows([txn({ amount: 1200 })], money);
    // Date is UTC-formatted, not local — Transaction.date is a date-only value
    // stored at UTC midnight and TZ is pinned west of UTC for this file.
    expect(row[0]).toContain("2026");
    expect(row[1]).toBe("expense");
    expect(row[2]).toBe("Infrastructure");
    expect(row[4]).toBe("Ayesha");
    expect(row[5]).toBe("- PKR 1200.00");
  });

  it("signs an inflow with + and an outflow with -", () => {
    const rows = pdfTransactionRows(
      [txn({ type: "expense", amount: 10 }), txn({ type: "investment", amount: 10 })],
      money
    );
    expect(rows[0][5].startsWith("-")).toBe(true);
    expect(rows[1][5].startsWith("+")).toBe(true);
  });
});

describe("the PDF and the Excel sheet agree about every row", () => {
  it("prints the identical description cell in both files", () => {
    const txns = [
      txn({ id: "a", description: LONG }),
      txn({ id: "b", description: "Short one" }),
      txn({ id: "c", description: "x".repeat(500) }),
    ];
    const pdf = pdfTransactionRows(txns, money);
    const xls = excelTransactionRows(txns);
    expect(pdf.length).toBe(xls.length);
    pdf.forEach((row, i) => {
      expect(row[TXN_DESCRIPTION_COL]).toBe(xls[i][TXN_DESCRIPTION_COL]);
    });
  });

  it("agrees on type, category and who added the row", () => {
    const txns = [txn()];
    const pdf = pdfTransactionRows(txns, money);
    const xls = excelTransactionRows(txns);
    expect(pdf[0][1]).toBe(xls[0][1]);
    expect(pdf[0][2]).toBe(xls[0][2]);
    expect(pdf[0][4]).toBe(xls[0][4]);
  });

  it("keeps the Excel amount a signed NUMBER, so the column can be summed", () => {
    const xls = excelTransactionRows([
      txn({ type: "expense", amount: 40 }),
      txn({ type: "income", amount: 40 }),
    ]);
    expect(xls[0][5]).toBe(-40);
    expect(xls[1][5]).toBe(40);
  });
});

describe("the exporter no longer truncates, and cannot silently start again", () => {
  const SOURCE = readFileSync(
    join(process.cwd(), "app", "(app)", "reports", "reports-client.tsx"),
    "utf8"
  );

  it("has no slice-based description cap left in the file", () => {
    // Text-level, deliberately: the behavioural cases above pass for any cap
    // above 45, so this is what stops the next edit re-introducing a 60- or
    // 100-character one. The `…` in a comment or in customer copy is fine; a
    // `.slice(` on a description is not.
    expect(SOURCE).not.toMatch(/description\s*\.\s*slice\s*\(/);
    expect(SOURCE).not.toMatch(/description\.length\s*>\s*\d+/);
  });

  it("gives the description column an explicit width so autoTable wraps it", () => {
    // Removing the cap without widening the column would let a 500-character
    // cell steal width from the amounts — a different way to lose the figure.
    expect(SOURCE).toMatch(/\[TXN_DESCRIPTION_COL\]:\s*\{\s*cellWidth:/);
  });
});
