"use client";

import { useId, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowDown, ArrowUp, Calendar, Pause, Play, Plus, Repeat, Trash2 } from "lucide-react";
import toast from "react-hot-toast";
import {
  createRecurringRuleAction,
  deleteRecurringRuleAction,
  toggleRecurringRuleAction,
} from "@/lib/actions/recurring";
import { z } from "zod";
import { NewRecurringRuleSchema, type NewRecurringRuleInput } from "@/lib/schemas/recurring";

/**
 * Form-level schema: a flat object that always has BOTH day fields, with
 * runtime refinement that the correct one is set for the chosen frequency.
 * We need this because react-hook-form keeps both fields registered at all
 * times (so toggling the segmented control doesn't drop user input), but
 * the server-side NewRecurringRuleSchema is a discriminated union and
 * rejects payloads that carry the wrong day field.
 *
 * At submit time we narrow this flat shape into the discriminated union
 * before calling the server action.
 */
const FormSchema = z
  .object({
    type: z.enum(["expense", "investment"]),
    amount: z
      .number({ invalid_type_error: "Amount must be a number" })
      .positive("Amount must be greater than 0")
      .max(1_000_000_000, "Amount is implausibly large"),
    category: z.string().min(1, "Pick a category"),
    description: z.string().trim().max(500),
    frequency: z.enum(["monthly", "weekly"]),
    dayOfMonth: z.number().int().min(1).max(31).optional(),
    dayOfWeek: z.number().int().min(0).max(6).optional(),
  })
  .refine((d) => (d.frequency === "monthly" ? d.dayOfMonth != null : d.dayOfWeek != null), {
    message: "Pick a day for the chosen frequency",
    path: ["dayOfMonth"],
  });

type FormSchemaInput = z.infer<typeof FormSchema>;
import { Modal } from "@/components/ui/modal";
import { useConfirm } from "@/components/ui/confirm-dialog";
import { Avatar } from "@/components/ui/avatar";
import { EmptyState } from "@/components/ui/empty-state";
import { PillBadge } from "@/components/landing/pill-badge";
import { cn, formatCurrency } from "@/lib/utils";
import { EXPENSE_CATEGORIES, INVESTMENT_CATEGORIES, type TransactionType } from "@/lib/types";
import type { RecurringRuleClient } from "@/lib/queries/recurring";

const DAY_NAMES = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

type Props = {
  rules: RecurringRuleClient[];
  currentUserId: string;
  currentUserRole: "admin" | "cofounder" | "member";
};

export function RecurringClient({ rules, currentUserId, currentUserRole }: Props) {
  const router = useRouter();
  const confirm = useConfirm();
  const [, startTransition] = useTransition();
  const [modalOpen, setModalOpen] = useState(false);
  const [pendingId, setPendingId] = useState<string | null>(null);

  function refresh() {
    startTransition(() => router.refresh());
  }

  async function handleToggle(rule: RecurringRuleClient) {
    setPendingId(rule.id);
    const res = await toggleRecurringRuleAction({ ruleId: rule.id, active: !rule.active });
    setPendingId(null);
    if (res.success) {
      toast.success(rule.active ? "Rule paused" : "Rule resumed");
      refresh();
    } else {
      toast.error(res.error);
    }
  }

  async function handleDelete(rule: RecurringRuleClient) {
    const ok = await confirm({
      title: "Delete this recurring rule?",
      description:
        "Past transactions generated by this rule stay in history; only the future schedule stops.",
      confirmLabel: "Delete",
      tone: "danger",
    });
    if (!ok) return;
    setPendingId(rule.id);
    const res = await deleteRecurringRuleAction(rule.id);
    setPendingId(null);
    if (res.success) {
      toast.success("Rule deleted");
      refresh();
    } else {
      toast.error(res.error);
    }
  }

  return (
    <div className="mx-auto max-w-[1200px] space-y-8">
      <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
        <div>
          <PillBadge tone="cyan">On schedule</PillBadge>
          <h1 className="mt-4 text-balance text-4xl font-bold tracking-tight md:text-5xl">
            Recurring
          </h1>
          <p className="mt-2 text-sm text-fg-muted md:text-base">
            Rent, salaries, subscriptions — set them up once and they post on their own. A daily job
            creates the next instance when it&apos;s due.
          </p>
        </div>
        <button
          onClick={() => setModalOpen(true)}
          className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-2.5 text-sm font-bold text-primary-fg shadow-[0_0_30px_rgb(182_244_37_/_var(--glow-shadow-opacity))] transition-transform hover:scale-[1.02] active:scale-95"
        >
          <Plus className="h-4 w-4" aria-hidden="true" /> New rule
        </button>
      </header>

      {rules.length === 0 ? (
        <div className="rounded-2xl border border-border bg-surface">
          <EmptyState
            icon={Repeat}
            title="No recurring rules yet"
            description="Set up a monthly office rent or a weekly subscription and stop logging it by hand."
            action={
              <button
                onClick={() => setModalOpen(true)}
                className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-2.5 text-sm font-bold text-primary-fg shadow-[0_0_30px_rgb(182_244_37_/_var(--glow-shadow-opacity))] transition-transform hover:scale-[1.02] active:scale-95"
              >
                <Plus className="h-4 w-4" aria-hidden="true" /> Add first rule
              </button>
            }
          />
        </div>
      ) : (
        <section className="grid grid-cols-1 gap-4 md:grid-cols-2">
          {rules.map((rule) => (
            <RuleCard
              key={rule.id}
              rule={rule}
              currentUserId={currentUserId}
              currentUserRole={currentUserRole}
              pending={pendingId === rule.id}
              onToggle={() => handleToggle(rule)}
              onDelete={() => handleDelete(rule)}
            />
          ))}
        </section>
      )}

      <Modal
        open={modalOpen}
        onClose={() => setModalOpen(false)}
        title="New recurring rule"
        description="Pick how often and which day — we'll create the first transaction right away."
        size="lg"
      >
        <NewRuleForm
          onClose={() => setModalOpen(false)}
          onCreated={() => {
            refresh();
            setModalOpen(false);
          }}
        />
      </Modal>
    </div>
  );
}

function RuleCard({
  rule,
  currentUserId,
  currentUserRole,
  pending,
  onToggle,
  onDelete,
}: {
  rule: RecurringRuleClient;
  currentUserId: string;
  currentUserRole: "admin" | "cofounder" | "member";
  pending: boolean;
  onToggle: () => void;
  onDelete: () => void;
}) {
  const canManage = rule.addedBy === currentUserId || currentUserRole === "admin";
  const frequencyLabel =
    rule.frequency === "monthly"
      ? `Monthly · day ${rule.dayOfMonth}`
      : `Weekly · ${DAY_NAMES[rule.dayOfWeek ?? 0]}`;
  const last = rule.lastMaterializedAt ? new Date(rule.lastMaterializedAt) : null;

  return (
    <article
      className={cn(
        "relative overflow-hidden rounded-2xl border bg-surface p-6 transition-opacity",
        rule.active ? "border-border" : "border-border/40 opacity-70"
      )}
    >
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0 flex-1">
          <div className="mb-2 flex items-center gap-2">
            <span
              className={cn(
                "inline-flex items-center gap-1 rounded-full border px-2.5 py-0.5 font-mono text-[10px] font-bold uppercase tracking-wider",
                rule.type === "expense"
                  ? "border-pink/30 bg-pink/10 text-pink-strong"
                  : "border-primary/30 bg-primary/10 text-primary-strong"
              )}
            >
              {rule.type === "expense" ? (
                <ArrowDown className="h-3 w-3" aria-hidden="true" />
              ) : (
                <ArrowUp className="h-3 w-3" aria-hidden="true" />
              )}
              {rule.type}
            </span>
            <span className="inline-flex items-center gap-1 rounded-full border border-cyan/30 bg-cyan/10 px-2.5 py-0.5 font-mono text-[10px] font-bold uppercase tracking-wider text-cyan-strong">
              <Repeat className="h-3 w-3" aria-hidden="true" /> {rule.frequency}
            </span>
            {!rule.active && (
              <span className="rounded-full bg-glass/[0.06] px-2 py-0.5 font-mono text-[10px] font-bold uppercase tracking-wider text-fg-muted">
                Paused
              </span>
            )}
          </div>
          <h3 className="truncate text-lg font-bold text-fg">{rule.category}</h3>
          {rule.description && (
            <p className="mt-1 line-clamp-2 text-sm text-fg-muted">{rule.description}</p>
          )}
        </div>
        <p
          className={cn(
            "shrink-0 font-mono text-lg font-bold tabular-nums",
            rule.type === "expense" ? "text-pink-strong" : "text-primary-strong"
          )}
        >
          {formatCurrency(rule.amount)}
        </p>
      </div>

      <div className="mt-5 grid grid-cols-3 gap-3 border-t border-border pt-4 text-xs">
        <div>
          <p className="font-mono text-[10px] uppercase tracking-wider text-fg-muted">Frequency</p>
          <p className="mt-1 flex items-center gap-1 font-medium text-fg">
            <Calendar className="h-3 w-3 text-fg-muted" aria-hidden="true" />
            {frequencyLabel}
          </p>
        </div>
        <div>
          <p className="font-mono text-[10px] uppercase tracking-wider text-fg-muted">Created</p>
          <p className="mt-1 flex items-center gap-1.5 font-medium text-fg">
            <Avatar name={rule.addedByName} size="xs" />
            <span className="truncate">{rule.addedByName.split(" ")[0]}</span>
          </p>
        </div>
        <div>
          <p className="font-mono text-[10px] uppercase tracking-wider text-fg-muted">Generated</p>
          <p className="mt-1 font-medium text-fg">
            {rule.materializedCount} txn{rule.materializedCount === 1 ? "" : "s"}
          </p>
        </div>
      </div>

      {last && (
        <p className="mt-3 font-mono text-[10px] uppercase tracking-wider text-fg-muted">
          Last fired {last.toLocaleDateString()}
        </p>
      )}

      {canManage && (
        <div className="mt-5 flex items-center justify-end gap-2 border-t border-border pt-4">
          <button
            onClick={onToggle}
            disabled={pending}
            className="inline-flex items-center gap-1.5 rounded-full border border-border bg-bg px-3 py-1.5 text-xs font-medium text-fg-muted transition-colors hover:bg-surface-hover hover:text-fg disabled:opacity-50"
          >
            {rule.active ? (
              <>
                <Pause className="h-3.5 w-3.5" aria-hidden="true" /> Pause
              </>
            ) : (
              <>
                <Play className="h-3.5 w-3.5" aria-hidden="true" /> Resume
              </>
            )}
          </button>
          <button
            onClick={onDelete}
            disabled={pending}
            aria-label={`Delete rule for ${rule.category}`}
            className="inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs font-medium text-danger transition-colors hover:bg-danger/10 disabled:opacity-50"
          >
            <Trash2 className="h-3.5 w-3.5" aria-hidden="true" /> Delete
          </button>
        </div>
      )}
    </article>
  );
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* NewRuleForm                                                                  */
/* ─────────────────────────────────────────────────────────────────────────── */

function NewRuleForm({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) {
  const amountId = useId();
  const categoryId = useId();
  const dayId = useId();
  const descId = useId();

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors, isSubmitting },
  } = useForm<FormSchemaInput>({
    resolver: zodResolver(FormSchema),
    mode: "onSubmit",
    reValidateMode: "onChange",
    defaultValues: {
      type: "expense",
      amount: undefined as unknown as number,
      category: EXPENSE_CATEGORIES[0],
      description: "",
      frequency: "monthly",
      dayOfMonth: 1,
    },
  });

  const type = watch("type");
  const frequency = watch("frequency");
  const categories = useMemo(
    () => (type === "expense" ? EXPENSE_CATEGORIES : INVESTMENT_CATEGORIES),
    [type]
  );

  async function onSubmit(data: FormSchemaInput) {
    // Narrow the flat form shape into the discriminated union the server
    // action expects. The FormSchema refinement above already guaranteed
    // the right day field is set for the chosen frequency.
    const payload: NewRecurringRuleInput =
      data.frequency === "monthly"
        ? {
            type: data.type,
            amount: data.amount,
            category: data.category,
            description: data.description,
            frequency: "monthly",
            dayOfMonth: data.dayOfMonth ?? 1,
          }
        : {
            type: data.type,
            amount: data.amount,
            category: data.category,
            description: data.description,
            frequency: "weekly",
            dayOfWeek: data.dayOfWeek ?? 1,
          };

    const res = await createRecurringRuleAction(payload);
    if (res.success) {
      toast.success("Rule created — first transaction logged");
      onCreated();
    } else {
      toast.error(res.error);
    }
  }

  function inputClass(hasError: boolean) {
    return cn(
      "w-full rounded-xl border bg-bg px-4 py-2.5 text-sm text-fg placeholder:text-fg-muted/60 transition-colors focus:bg-surface focus:outline-none",
      hasError ? "border-danger/60 focus:border-danger" : "border-border focus:border-primary/50"
    );
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5" noValidate>
      <div>
        <p className="mb-2 font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-fg-muted">
          Type
        </p>
        <div className="grid grid-cols-2 gap-2">
          {(["expense", "investment"] as const).map((t) => (
            <button
              key={t}
              type="button"
              onClick={() => {
                setValue("type", t, { shouldValidate: false });
                // Reset category to a valid one for the new type.
                setValue(
                  "category",
                  (t === "expense" ? EXPENSE_CATEGORIES : INVESTMENT_CATEGORIES)[0]
                );
              }}
              aria-pressed={type === t}
              className={cn(
                "rounded-xl border px-3 py-2.5 text-sm font-medium transition-all",
                type === t
                  ? "border-primary/50 bg-primary/[0.06] text-fg ring-2 ring-primary/20"
                  : "border-border text-fg-muted hover:border-primary/30 hover:text-fg"
              )}
            >
              {t === "expense" ? "Expense" : "Investment"}
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-2 gap-3">
        <div>
          <label
            htmlFor={amountId}
            className="mb-2 block font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-fg-muted"
          >
            Amount (PKR)
          </label>
          <input
            id={amountId}
            type="number"
            inputMode="decimal"
            min="0"
            step="0.01"
            placeholder="0.00"
            {...register("amount", { valueAsNumber: true })}
            className={inputClass(!!errors.amount)}
          />
          {errors.amount && <p className="mt-1.5 text-xs text-danger">{errors.amount.message}</p>}
        </div>
        <div>
          <label
            htmlFor={categoryId}
            className="mb-2 block font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-fg-muted"
          >
            Category
          </label>
          <select
            id={categoryId}
            {...register("category")}
            className={inputClass(!!errors.category)}
          >
            {categories.map((c) => (
              <option key={c} value={c} className="bg-bg">
                {c}
              </option>
            ))}
          </select>
          {errors.category && (
            <p className="mt-1.5 text-xs text-danger">{errors.category.message}</p>
          )}
        </div>
      </div>

      <div>
        <label
          htmlFor={descId}
          className="mb-2 block font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-fg-muted"
        >
          Description
        </label>
        <input
          id={descId}
          placeholder="Office rent / Team subscription / etc."
          {...register("description")}
          className={inputClass(!!errors.description)}
        />
        {errors.description && (
          <p className="mt-1.5 text-xs text-danger">{errors.description.message}</p>
        )}
      </div>

      <div>
        <p className="mb-2 font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-fg-muted">
          Frequency
        </p>
        <div className="grid grid-cols-2 gap-2">
          {(["monthly", "weekly"] as const).map((f) => (
            <button
              key={f}
              type="button"
              onClick={() => {
                setValue("frequency", f, { shouldValidate: false });
                if (f === "monthly") {
                  setValue("dayOfMonth", 1);
                  setValue("dayOfWeek", undefined);
                } else {
                  setValue("dayOfWeek", 1); // Monday default
                  setValue("dayOfMonth", undefined);
                }
              }}
              aria-pressed={frequency === f}
              className={cn(
                "rounded-xl border px-3 py-2.5 text-sm font-medium transition-all",
                frequency === f
                  ? "border-primary/50 bg-primary/[0.06] text-fg ring-2 ring-primary/20"
                  : "border-border text-fg-muted hover:border-primary/30 hover:text-fg"
              )}
            >
              {f === "monthly" ? "Monthly" : "Weekly"}
            </button>
          ))}
        </div>
      </div>

      {frequency === "monthly" ? (
        <div>
          <label
            htmlFor={dayId}
            className="mb-2 block font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-fg-muted"
          >
            Day of month
          </label>
          <input
            id={dayId}
            type="number"
            inputMode="numeric"
            min="1"
            max="31"
            {...register("dayOfMonth", { valueAsNumber: true })}
            className={inputClass(!!errors.dayOfMonth)}
          />
          <p className="mt-1.5 text-xs text-fg-muted">
            If a month has fewer days (e.g. 31 in Feb), the rule fires on the last day instead.
          </p>
          {errors.dayOfMonth && (
            <p className="mt-1.5 text-xs text-danger">{errors.dayOfMonth.message}</p>
          )}
        </div>
      ) : (
        <div>
          <p className="mb-2 font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-fg-muted">
            Day of week
          </p>
          <div className="grid grid-cols-7 gap-1.5">
            {DAY_NAMES.map((name, i) => {
              const active = watch("dayOfWeek") === i;
              return (
                <button
                  key={name}
                  type="button"
                  onClick={() => setValue("dayOfWeek", i, { shouldValidate: false })}
                  aria-pressed={active}
                  className={cn(
                    "rounded-lg border px-1 py-2 text-xs font-medium transition-all",
                    active
                      ? "border-primary/50 bg-primary/[0.06] text-fg ring-2 ring-primary/20"
                      : "border-border text-fg-muted hover:border-primary/30 hover:text-fg"
                  )}
                >
                  {name}
                </button>
              );
            })}
          </div>
          {errors.dayOfWeek && (
            <p className="mt-1.5 text-xs text-danger">{errors.dayOfWeek.message}</p>
          )}
        </div>
      )}

      <div className="flex gap-3 border-t border-border pt-4">
        <button
          type="button"
          onClick={onClose}
          className="flex-1 rounded-full border border-border bg-bg px-5 py-2.5 text-sm font-medium text-fg transition-colors hover:bg-surface-hover"
        >
          Cancel
        </button>
        <button
          type="submit"
          disabled={isSubmitting}
          className="inline-flex flex-1 items-center justify-center gap-2 rounded-full bg-primary px-5 py-2.5 text-sm font-bold text-primary-fg shadow-[0_0_30px_rgb(182_244_37_/_var(--glow-shadow-opacity))] transition-transform hover:scale-[1.01] active:scale-95 disabled:opacity-60 disabled:hover:scale-100"
        >
          {isSubmitting ? "Creating…" : "Create rule"}
        </button>
      </div>
    </form>
  );
}
